### ISSUE TITLE
Failed to unwrap file key for file error

### ISSUE THREAD

**Issue by lordm** [hackappcom/iloot#12]
The tool is working perfectly, but this time there's a file that is doesn't download correctly and  gives me 
Failed to unwrap file key for file Documents/ChatStorage.sqlite !!!
What does the error mean ? and how can it be fixed ?

**Comment by jetXS** [comment]
got the same error for a lot of my files.

exemple: Failed to unwrap file key for file Media/Recordings/20141215 150555.waveform !!!

**Comment by xlbillyboylx** [comment]
yep same here, a lot of failed to unwrap file key errors.

**Comment by rrover** [comment]
This issue is happening again now, something changed to the encryption method again?

**Comment by 9rga** [comment]
You have to check file protection level, if it's equal 3 (NSFileProtectionCompleteUntilFirstUserAuthentication) file can'not be decrypted now, because:
> NSFileProtectionCompleteUnlessOpen - file is encrypted and can only be opened when the device is unlocked. Once open, the file can continue to accessed even if the user locks the device.
