### ISSUE TITLE
IndexError: list index out of range - in iloot.py

### ISSUE THREAD

**Issue by AddaxSoft** [hackappcom/iloot#19]
I faced this error during fetching backup files from icloud servers
This crash precisely happens when I download full backup not just a particular domain. 

```
CameraRollDomain 	./output/_____UDID[hidden]_____/snapshot_1/CameraRollDomain/Media/DCIM/101APPLE/IMG_1965.JPG
chunk decryption Failed
chunk decryption Failed
Traceback (most recent call last):
  File "iloot.py", line 610, in <module>
    download_backup(args.apple_id, args.password, args.output, args.item_types, args.snapshot, args.combined, args.itunes_style, args.domain)
  File "iloot.py", line 572, in download_backup
    client.download(UDID, types)
  File "iloot.py", line 450, in download
    self.authorize_get(authTokens, snapshot)
  File "iloot.py", line 256, in authorize_get
    decrypted_chunks[i] = data[reference.chunk_index]
IndexError: list index out of range
```

This could be an integer overflow or a memory leak.

**Comment by jetXS** [comment]
Got the same error happening in the same condition.

**Comment by BrainRift** [comment]
I am having the same issue when I attempt a full backup, but if I specify a domain, so far it has been working.

**Comment by yeukhon** [comment]
Indeed. This issue is not allowing me to download photos...

**Comment by BrainRift** [comment]
Thank you !

**Comment by yeukhon** [comment]
There is a some bg to fix. Some files will fail to decrypt BUT at least you can get most of the files... FYI.
