### ISSUE TITLE
Problem with installing requirements

### ISSUE THREAD

**Issue by Batze93** [hackappcom/iloot#39]
I have a problem with pip and the requirements.txt

I tried everything :( What is the command "make"?

------------------------------------------------------------
C:\Python27\Scripts\pip run on 04/14/15 21:16:00
Downloading/unpacking gevent from git+https://github.com/cloudflare/gevent.git (from -r requirements.txt (line 1))
  Cloning https://github.com/cloudflare/gevent.git to c:\users\diebolpa\appdata\local\temp\pip_build_diebolpa\gevent
  Found command 'git' at 'C:\\Users\\DiebolPa\\AppData\\Local\\GitHub\\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\\bin\\git.exe'
  Running command C:\Users\DiebolPa\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\bin\git.exe clone -q https://github.com/cloudflare/gevent.git c:\users\diebolpa\appdata\local\temp\pip_build_DiebolPa\gevent
  Running setup.py (path:c:\users\diebolpa\appdata\local\temp\pip_build_DiebolPa\gevent\setup.py) egg_info for package gevent
    running egg_info
    creating pip-egg-info\gevent.egg-info
    writing requirements to pip-egg-info\gevent.egg-info\requires.txt
    writing pip-egg-info\gevent.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\gevent.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\gevent.egg-info\dependency_links.txt
    writing manifest file 'pip-egg-info\gevent.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info\gevent.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'Makefile.ext'
    writing manifest file 'pip-egg-info\gevent.egg-info\SOURCES.txt'
    
    WARNING: The gevent.ares extension has been disabled.
  Source in c:\users\diebolpa\appdata\local\temp\pip_build_diebolpa\gevent has version 1.1, which satisfies requirement gevent from git+https://github.com/cloudflare/gevent.git (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): hurry.filesize in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): pycrypto in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): protobuf in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): greenlet in c:\python27\lib\site-packages (from gevent->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\python27\lib\site-packages (from hurry.filesize->-r requirements.txt (line 2))
Installing collected packages: gevent
  Running setup.py install for gevent
    Running command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\diebolpa\\appdata\\local\\temp\\pip_build_DiebolPa\\gevent\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\diebolpa\appdata\local\temp\pip-r91d_w-record\install-record.txt --single-version-externally-managed --compile
    Der Befehl "make" ist entweder falsch geschrieben oder
    konnte nicht gefunden werden.
    Running 'make' in c:\users\diebolpa\appdata\local\temp\pip_build_DiebolPa\gevent
    Complete output from command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\diebolpa\\appdata\\local\\temp\\pip_build_DiebolPa\\gevent\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\diebolpa\appdata\local\temp\pip-r91d_w-record\install-record.txt --single-version-externally-managed --compile:
    Der Befehl "make" ist entweder falsch geschrieben oder

konnte nicht gefunden werden.

Running 'make' in c:\users\diebolpa\appdata\local\temp\pip_build_DiebolPa\gevent

----------------------------------------
Cleaning up...
  Removing temporary dir c:\users\diebolpa\appdata\local\temp\pip_build_DiebolPa...
Command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\diebolpa\\appdata\\local\\temp\\pip_build_DiebolPa\\gevent\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\diebolpa\appdata\local\temp\pip-r91d_w-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in c:\users\diebolpa\appdata\local\temp\pip_build_DiebolPa\gevent
Exception information:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "C:\Python27\lib\site-packages\pip\req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "C:\Python27\lib\site-packages\pip\req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "C:\Python27\lib\site-packages\pip\util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\diebolpa\\appdata\\local\\temp\\pip_build_DiebolPa\\gevent\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\diebolpa\appdata\local\temp\pip-r91d_w-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in c:\users\diebolpa\appdata\local\temp\pip_build_DiebolPa\gevent

**Comment by Marfusios** [comment]
Change line in requirements.txt from "git+https://github.com/cloudflare/gevent.git#egg=gevent" to just "gevent". 
Library gevent is already saved as package - https://pypi.python.org/pypi/gevent

**Comment by hackappcom** [comment]
changed
